apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-frontend
data:
  VITE_API_URL: https://lol.kub.sspcloud.fr
  VITE_ENVIRONNEMENT: sspcloud-pd
  __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: "lol-app.kub.sspcloud.fr"