name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pylint Black Flake8 Isort
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Formatting checks black
      run: 
        python -m black --check backend/app        
    - name: Flake8
      run: |
        python -m flake8 backend/app      
    - name: Linting with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under 5        
    - name: Formatting checks isort
      run: |
        python -m isort --profile black --check backend/app       

